---
title: "2021-04"
description: |
   情報システム導入に関する月次報告書
author:
  - name: Yusei Kawai
    url: https://example.com/norajones
date: 04-22-2021
output:
  distill::distill_article:
    TOC: true
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



# 1. Document Management System
### Overview & Milestone
* [文書管理システムWBS参照](https://www.notion.so/ed6dcca847ad45d396de0e79a217d6bd?v=5846dc73e818443081e8d0c721435b44)

### Heighlight
* アガサ（Agatha）/NRI（PermaDoc）/Qualio RFI実施。
* アガサ、NRIについては質問事項をまとめた上でQ&A打ち合わせを追加実施。
* GVP/QAワークショップ実施。システム化に向けたプロセスの見える化を依頼。
* テスト環境を用いたシステム検証プロトコルを作成。

### Milestone
* [文書管理システムWBS参照](https://www.notion.so/ed6dcca847ad45d396de0e79a217d6bd?v=5846dc73e818443081e8d0c721435b44)

### Risk & Concerns
* CSV実施要領参照

### 来月の予定
* テスト環境を用いたシステム検証（Agatha / PermaDoc / Verji）とシステムの絞り込み。
* ワークショップ with 臨床開発部
* ベンダー調達管理。
<br>


## 2. SAP / WMS
### Overview & Milestone
* CSV帳票の内容合意
* SAP/WMS運用方法の作成開始
* IFテスト終盤

### Heighlight
* WMSの仕様確認。仕様をもとに安田倉庫の運用フロー修正。
* CSVマスタープラン、実施要領、要件定義の内容合意。
* IFテスト進行中。

### Milestone
* 「マスタープラン 実施期間」のセッション参照。 6月までにマスタープラン、実施要領、要件定義書をまとめる。

### Risk & Concerns
* 6月実施予定のUATまでにテスト計画書が構築できない。

### 来月の予定
* マスタープラン、実施要領、要件定義書の記載整備と承認回覧。
* QMS購買管理。
<br>


## 3. e-learning System
### Overview & Milestone
* [ナレッジデリWBS参照](https://www.notion.so/60cbfdfcf0d04703890693efe5c8ca43?v=98acbc6ce2024e69a172570f4662de21)

### Heighlight
* 各部門との意見交換とその分析

### Milestone
* [ナレッジデリWBS参照](https://www.notion.so/60cbfdfcf0d04703890693efe5c8ca43?v=98acbc6ce2024e69a172570f4662de21)

### Risk & Concerns方針決定
* CSV実施要領参照

### 来月の予定
* 社内展開の進め方検討
* 稟議書作成
* （必要に応じ）役員へ説明
